module.exports = {
    '1': '1',
    '2': 'to',
    'tre': 'pilt',
    'væbner': 'trop',
    'senior': 'fråseri',
    'vrede': 'saturn',
    'uranus': '<span class="small">Morten Skrubbeltrang</span>',
    'Rasmus Agergaard Pedersen': '<span class="small">Du må ikke vidne falsk mod din næste</span>',
    'Du må ikke begære din næstes hus': 'theta',
    'iota': 'oktober',
    'november': 'knægt',
    'dame': 'Thea Gaming',
    'AquaHoldet': 'Aluminium',
    'Silicium': 'Livet i havet',
    'Livet på land': 'O',
    'P': '<span class="small">Otto Joachim Moltke</span>',
    'Poul Christian Stemann': 'Tocantins–Araguaia',
    'Volga': 'Køge',
    'Holstebro': '.---- ----.',
    '..--- -----': 'Raticate',
    'Spearow': '<span class="small">Tillykke, I har løst startopgaven!<br><br><a href="https://docs.google.com/forms/d/e/1FAIpQLScOA9AyF_hgRmiKTfKnpDu__YuRzk_c8pU-bMl_AdVGWvQWaA/formResponse">Find ud af hvor vi starter</a></span><style>form > br, input, label, button {display: none;}</style>'
}