module.exports = {
    '1': '1',
    '2': 'to',
    'tre': 'pilt',
    'væbner': 'trop',
    'klan': 'fråseri',
    'vrede': 'saturn',
    'uranus': '<span class="small">Morten Skrubbeltrang</span>',
    'Rasmus Agergaard Pedersen': '<span class="small">Du må ikke vidne falsk mod din næste</span>',
    'Du må ikke begære din næstes hus': 'theta',
    'iota': 'oktober',
    'november': 'knægt',
    'dame': 'UberDanger',
    'AquaHoldet': 'Aluminium',
    'Silicium': 'Livet i havet',
    'Livet på land': 'O',
    'P': 'Otto Joachim Moltke',
    'Poul Christian Stemann': 'Tocantins–Araguaia',
    'Volga': 'Køge',
    'Holstebro': '.---- ----.',
    '.---- -----': 'Raticate',
    'Spearow': '<span class="small">Tillykke, I har løst startopgaven!<br><br>Vi starter på Skagen Havn 🚢</span><style>form > br, input, label, button {display: none;}</style>'
}